<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="bhajandevi" ignored="0" name="Test1" tests="2" failures="2" timestamp="24 Sep 2021 07:19:21 GMT" time="0.248" errors="0">
  <testcase name="invalidLoginTest" time="0.077" classname="loginTests.AppTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at loginTests.AppTest.invalidLoginTest(AppTest.java:20)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest -->
  <testcase name="validLoginTest" time="0.009" classname="loginTests.AppTest">
    <failure type="java.lang.AssertionError" message="Login Failed with valid Credential expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Login Failed with valid Credential expected [true] but found [false]
at loginTests.AppTest.validLoginTest(AppTest.java:13)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- validLoginTest -->
</testsuite> <!-- Test1 -->
